#!/usr/bin/env bash

SOCKET="$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock"

if [[ -z "$HYPRLAND_INSTANCE_SIGNATURE" ]] || [[ ! -S "$SOCKET" ]]; then
    echo "Hyprland socket not found."
    exit 1
fi

socat -U - UNIX-CONNECT:"$SOCKET" | while read -r line; do
    if [[ "$line" == openwindow* ]]; then
        event_data="${line#*>>}"
        IFS=',' read -r address _ class title <<< "$event_data"

        if [[ "$title" == "util_is_kitty" ]]; then
            hyprctl dispatch resizewindowpixel 413 1002,title:\^\(util_is_kitty\)\$
        fi
    fi
done
